services: 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
  backend:
    build: ./backend
    volumes:
      - ./my_local_uploads:/home/node/app/uploads
    ports:
      - "3000-3002:3000"
    restart: always
    deploy:
     replicas: 1
    env_file:
      - ./backend/.env
  ai:
    build: ./ai
    ports:
      - "8000:8000"
    restart: always
    deploy:
     replicas: 1
    environment:
      - DOMAIN=www.imageflow.atulyadav.tech